//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TAIKHOAN
    {
        [DisplayName("TenDN")]
        [Required(ErrorMessage = "Error Empty")]

        public string TenDN { get; set; }
        [DisplayName("MatKhau")]
        [Required(ErrorMessage = "Error Empty")]
        public string MatKhau { get; set; }
        [DisplayName("PhanQuyen")]
        [Required(ErrorMessage = "Error Empty")]
        public string PhanQuyen { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Error Empty")]
        [Compare("MatKhau")]
        public string Repass { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
